// Code generated by protoc-gen-go.
// source: manifest.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	manifest.proto

It has these top-level messages:
	Manifest
	Resource
	XAttr
	ADSEntry
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Manifest specifies the entries in a container bundle, keyed and sorted by
// path.
type Manifest struct {
	Resource []*Resource `protobuf:"bytes,1,rep,name=resource" json:"resource,omitempty"`
}

func (m *Manifest) Reset()                    { *m = Manifest{} }
func (m *Manifest) String() string            { return proto1.CompactTextString(m) }
func (*Manifest) ProtoMessage()               {}
func (*Manifest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Manifest) GetResource() []*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Resource struct {
	// Path specifies the path from the bundle root. If more than one
	// path is present, the entry may represent a hardlink, rather than using
	// a link target. The path format is operating system specific.
	Path []string `protobuf:"bytes,1,rep,name=path" json:"path,omitempty"`
	// Uid specifies the user id for the resource.
	Uid int64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	// Gid specifies the group id for the resource.
	Gid int64 `protobuf:"varint,3,opt,name=gid" json:"gid,omitempty"`
	// user and group are not currently used but their field numbers have been
	// reserved for future use. As such, they are marked as deprecated.
	User  string `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	Group string `protobuf:"bytes,5,opt,name=group" json:"group,omitempty"`
	// Mode defines the file mode and permissions. We've used the same
	// bit-packing from Go's os package,
	// http://golang.org/pkg/os/#FileMode, since they've done the work of
	// creating a cross-platform layout.
	Mode uint32 `protobuf:"varint,6,opt,name=mode" json:"mode,omitempty"`
	// Size specifies the size in bytes of the resource. This is only valid
	// for regular files.
	Size uint64 `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	// Digest specifies the content digest of the target file. Only valid for
	// regular files. The strings are formatted in OCI style, i.e. <alg>:<encoded>.
	// For detailed information about the format, please refer to OCI Image Spec:
	// https://github.com/opencontainers/image-spec/blob/master/descriptor.md#digests-and-verification
	// The digests are sorted in lexical order and implementations may choose
	// which algorithms they prefer.
	Digest []string `protobuf:"bytes,8,rep,name=digest" json:"digest,omitempty"`
	// Target defines the target of a hard or soft link. Absolute links start
	// with a slash and specify the resource relative to the bundle root.
	// Relative links do not start with a slash and are relative to the
	// resource path.
	Target string `protobuf:"bytes,9,opt,name=target" json:"target,omitempty"`
	// Major specifies the major device number for character and block devices.
	Major uint64 `protobuf:"varint,10,opt,name=major" json:"major,omitempty"`
	// Minor specifies the minor device number for character and block devices.
	Minor uint64 `protobuf:"varint,11,opt,name=minor" json:"minor,omitempty"`
	// Xattr provides storage for extended attributes for the target resource.
	Xattr []*XAttr `protobuf:"bytes,12,rep,name=xattr" json:"xattr,omitempty"`
	// Ads stores one or more alternate data streams for the target resource.
	Ads []*ADSEntry `protobuf:"bytes,13,rep,name=ads" json:"ads,omitempty"`
	// Timestamps.
	// btime (birthtime) is available on Darwin, FreeBSD, NetBSD, and Windows.
	// When btime is unknown, it SHOULD be set to zero.
	Atime *google_protobuf.Timestamp `protobuf:"bytes,14,opt,name=atime" json:"atime,omitempty"`
	Mtime *google_protobuf.Timestamp `protobuf:"bytes,15,opt,name=mtime" json:"mtime,omitempty"`
	Ctime *google_protobuf.Timestamp `protobuf:"bytes,16,opt,name=ctime" json:"ctime,omitempty"`
	Btime *google_protobuf.Timestamp `protobuf:"bytes,17,opt,name=btime" json:"btime,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto1.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Resource) GetXattr() []*XAttr {
	if m != nil {
		return m.Xattr
	}
	return nil
}

func (m *Resource) GetAds() []*ADSEntry {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *Resource) GetAtime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Atime
	}
	return nil
}

func (m *Resource) GetMtime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Mtime
	}
	return nil
}

func (m *Resource) GetCtime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *Resource) GetBtime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Btime
	}
	return nil
}

// XAttr encodes extended attributes for a resource.
type XAttr struct {
	// Name specifies the attribute name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Data specifies the associated data for the attribute.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *XAttr) Reset()                    { *m = XAttr{} }
func (m *XAttr) String() string            { return proto1.CompactTextString(m) }
func (*XAttr) ProtoMessage()               {}
func (*XAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// ADSEntry encodes information for a Windows Alternate Data Stream.
type ADSEntry struct {
	// Name specifices the stream name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Data specifies the stream data.
	// See also the description about the digest below.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Digest is a CAS representation of the stream data.
	//
	// At least one of data or digest MUST be specified, and either one of them
	// SHOULD be specified.
	//
	// How to access the actual data using the digest is implementation-specific,
	// and implementations can choose not to implement digest.
	// So, digest SHOULD be used only when the stream data is large.
	Digest string `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
}

func (m *ADSEntry) Reset()                    { *m = ADSEntry{} }
func (m *ADSEntry) String() string            { return proto1.CompactTextString(m) }
func (*ADSEntry) ProtoMessage()               {}
func (*ADSEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*Manifest)(nil), "proto.Manifest")
	proto1.RegisterType((*Resource)(nil), "proto.Resource")
	proto1.RegisterType((*XAttr)(nil), "proto.XAttr")
	proto1.RegisterType((*ADSEntry)(nil), "proto.ADSEntry")
}

func init() { proto1.RegisterFile("manifest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x0f, 0xd3, 0x30,
	0x10, 0xc5, 0x95, 0x26, 0x29, 0xe9, 0xf5, 0x2f, 0x16, 0xaa, 0x4e, 0x5d, 0x08, 0x99, 0x22, 0x21,
	0xa5, 0xa8, 0x0c, 0xcc, 0x45, 0xb0, 0x20, 0xb1, 0x18, 0x06, 0x56, 0xb7, 0x71, 0x83, 0x11, 0x8e,
	0x23, 0xc7, 0x91, 0x80, 0x2f, 0xc0, 0xd7, 0x46, 0x3e, 0x27, 0x15, 0x4c, 0x65, 0xea, 0xbd, 0x77,
	0xf7, 0x73, 0x9d, 0x7b, 0x86, 0x8d, 0x16, 0xad, 0xba, 0xc9, 0xde, 0x55, 0x9d, 0x35, 0xce, 0xb0,
	0x94, 0x7e, 0x0e, 0xcf, 0x1b, 0x63, 0x9a, 0xef, 0xf2, 0x48, 0xea, 0x32, 0xdc, 0x8e, 0x4e, 0x69,
	0xd9, 0x3b, 0xa1, 0xbb, 0x30, 0x57, 0xbc, 0x81, 0xec, 0xe3, 0x48, 0xb2, 0x97, 0x90, 0x59, 0xd9,
	0x9b, 0xc1, 0x5e, 0x25, 0x46, 0x79, 0x5c, 0x2e, 0x4f, 0xdb, 0x30, 0x55, 0xf1, 0xd1, 0xe6, 0xf7,
	0x81, 0xe2, 0x77, 0x02, 0xd9, 0x64, 0x33, 0x06, 0x49, 0x27, 0xdc, 0x57, 0xa2, 0x16, 0x9c, 0x6a,
	0xb6, 0x83, 0x78, 0x50, 0x35, 0xce, 0xf2, 0xa8, 0x8c, 0xb9, 0x2f, 0xbd, 0xd3, 0xa8, 0x1a, 0xe3,
	0xe0, 0x34, 0xaa, 0x66, 0x7b, 0x48, 0x86, 0x5e, 0x5a, 0x4c, 0xf2, 0xa8, 0x5c, 0xbc, 0x9d, 0x61,
	0xc4, 0x49, 0x33, 0x84, 0xb4, 0xb1, 0x66, 0xe8, 0x30, 0xbd, 0x37, 0x82, 0xe1, 0xff, 0x49, 0x9b,
	0x5a, 0xe2, 0x3c, 0x8f, 0xca, 0x35, 0xa7, 0xda, 0x7b, 0xbd, 0xfa, 0x25, 0xf1, 0x49, 0x1e, 0x95,
	0x09, 0xa7, 0x9a, 0xed, 0x61, 0x5e, 0xab, 0x46, 0xf6, 0x0e, 0x33, 0xba, 0xd3, 0xa8, 0xbc, 0xef,
	0x84, 0x6d, 0xa4, 0xc3, 0x85, 0x3f, 0x9a, 0x8f, 0x8a, 0x3d, 0x83, 0x54, 0x8b, 0x6f, 0xc6, 0x22,
	0xd0, 0x21, 0x41, 0x90, 0xab, 0x5a, 0x63, 0x71, 0x39, 0xba, 0x5e, 0xb0, 0x02, 0xd2, 0x1f, 0xc2,
	0x39, 0x8b, 0x2b, 0x5a, 0xd2, 0x6a, 0x5c, 0xd2, 0x97, 0xb3, 0x73, 0x96, 0x87, 0x16, 0x7b, 0x01,
	0xb1, 0xa8, 0x7b, 0x5c, 0xff, 0xb3, 0xc6, 0xf3, 0xbb, 0x4f, 0xef, 0x5b, 0x67, 0x7f, 0x72, 0xdf,
	0x63, 0xaf, 0x20, 0x15, 0x3e, 0x0e, 0xdc, 0xe4, 0x51, 0xb9, 0x3c, 0x1d, 0xaa, 0x90, 0x55, 0x35,
	0x65, 0x55, 0x7d, 0x9e, 0xb2, 0xe2, 0x61, 0xd0, 0x13, 0x9a, 0x88, 0xed, 0x63, 0x42, 0x4f, 0xc4,
	0x95, 0x88, 0xdd, 0x63, 0xe2, 0x3a, 0x11, 0x17, 0x22, 0x9e, 0x3e, 0x26, 0x68, 0xb0, 0x38, 0x42,
	0x4a, 0x9f, 0xee, 0x73, 0x68, 0x85, 0xf6, 0x6f, 0xc7, 0x6f, 0x96, 0x6a, 0xef, 0xd5, 0xc2, 0x09,
	0x7a, 0x06, 0x2b, 0x4e, 0x75, 0xf1, 0x01, 0xb2, 0x69, 0x13, 0xff, 0xcb, 0xfc, 0x95, 0x67, 0x1c,
	0x72, 0x0b, 0xea, 0x32, 0xa7, 0x7b, 0xbd, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xf0, 0xda,
	0x46, 0x00, 0x03, 0x00, 0x00,
}
